services:
  blog_prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=https://qcawlvgmohxhyztlmpqh.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjYXdsdmdtb2h4aHl6dGxtcHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIwMjUzNzMsImV4cCI6MjA0NzYwMTM3M30.wjmLdPzq8J2HGppq-ejLsCZj1v3vcuZdQ7k9GlvD06w
    volumes:
      # Exclude node_modules to use container's node_modules
      - /app/node_modules
    stdin_open: true
    tty: true
    restart: always