services:
  blog_prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      # Exclude node_modules to use container's node_modules
      - /app/node_modules
    stdin_open: true
    tty: true